name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build-dev-branch:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 11
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build & Test
        run: mvn -B clean verify

  build-maintenance-branch:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 8
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/v1.5.x'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build & Test
        run: mvn -B -Prun-its clean verify
